# Generated by Django 2.2.8 on 2020-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='genero',
            field=models.PositiveIntegerField(choices=[(1, 'Femenino'), (2, 'Masculino'), (3, 'Otros')]),
        ),
    ]
