# Generated by Django 3.0.8 on 2020-08-13 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('categoria', models.TextField(default='', max_length=255)),
                ('descripcion', models.TextField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'business_categories',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('nombre_local', models.CharField(default='', max_length=255)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateField(default=datetime.datetime(2020, 8, 13, 18, 14, 41, 259239, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField()),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Users Business',
                'db_table': 'user_business',
                'ordering': ('pk',),
                'unique_together': {('fk_user', 'nombre_local')},
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_delete', models.BooleanField(default=False)),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descripcion', models.TextField(default='', max_length=255)),
                ('precio_neto', models.FloatField(default=0.0)),
                ('porcentaje', models.IntegerField(default=0)),
                ('deshabilitado', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.datetime(2020, 8, 13, 18, 14, 41, 260231, tzinfo=utc), editable=False)),
                ('updated_at', models.DateTimeField()),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.UserBusiness')),
            ],
            options={
                'verbose_name': 'User Offer',
                'verbose_name_plural': 'User Offers',
                'db_table': 'business_offer',
                'ordering': ('pk',),
                'unique_together': {('fk_user', 'titulo')},
            },
        ),
    ]
